#ifndef V_FRAMEWORK_PLATFORMS_WINDOWS_CORE_SOCKET_VSOCKET_WINAPI_H
#define V_FRAMEWORK_PLATFORMS_WINDOWS_CORE_SOCKET_VSOCKET_WINAPI_H

#include <WinSock2.h>
#include <ws2tcpip.h>

#define SD_RECEIVE  0x00
#define SD_SEND     0x01
#define SD_BOTH     0x02


#endif // V_FRAMEWORK_PLATFORMS_WINDOWS_CORE_SOCKET_VSOCKET_WINAPI_H