#ifndef V_FRAMEWORK_CORE_STD_PARALLEL_WINDOWS_CONFIG_PLATFORM_H
#define V_FRAMEWORK_CORE_STD_PARALLEL_WINDOWS_CONFIG_PLATFORM_H

#include <../common/winapi/vcore/std/parallel/config_winapi.h>

#endif // V_FRAMEWORK_CORE_STD_PARALLEL_WINDOWS_CONFIG_PLATFORM_H