#ifndef V_FRAMEWORK_CORE_PLATFORM_WINDOWS_MATH_INTERNAL_MATH_TYPES_WINDOWS_H
#define V_FRAMEWORK_CORE_PLATFORM_WINDOWS_MATH_INTERNAL_MATH_TYPES_WINDOWS_H

#if V_TRAIT_USE_PLATFORM_SIMD_SSE
#   include <intrin.h>
#   include <xmmintrin.h>
#   include <pmmintrin.h>
#   include <emmintrin.h>
#endif

#endif // V_FRAMEWORK_CORE_PLATFORM_WINDOWS_MATH_INTERNAL_MATH_TYPES_WINDOWS_H