SET(FILES
    core/base.h
    core/variadic.h
    core/platform_incl.h
    core/platform.h
    core/platform.cc
    core/platform_default.h
    core/platform_restricted_file_default.h
    core/casting/lossy_cast.h
    core/casting/numeric_cast_internal.h
    core/casting/numeric_cast.h
    core/compression/compression.h
    core/compression/compression.cc 
    core/compression/zstd_compression.h 
    core/compression/zstd_compression.cc
    core/debug/trace.h 
    core/debug/stack_tracer.h
    core/debug/memory_profiler.h
    core/io/path/path.h
    core/io/path/path.cc
    core/io/path/path_fwd.h
    core/io/file_io.h  
    core/io/file_io.cc
    core/io/generic_streams.h
    core/io/generic_streams.cc
    core/io/io_utils.h
    core/io/io_utils.cc
    core/io/system_file.h
    core/io/system_file.cc
    core/ipc/shared_memory_common.h 
    core/ipc/shared_memory.h
    core/ipc/shared_memory.cc
    core/math/crc.h
    core/math/crc.cc
    core/math/random.h
    core/math/sha1.h
    core/memory/allocator_records.h
    core/memory/allocator_records.cc
    core/memory/allocator_base.h
    core/memory/allocator_base.cc
    core/memory/allocator_manager.h
    core/memory/allocator_manager.cc
    core/memory/allocator_override_shim.h
    core/memory/allocator_override_shim.cc
    core/memory/allocator_wrapper.h
    core/memory/config.h
    core/memory/heap_schema.h
    core/memory/heap_schema.cc
    core/memory/hpha_schema.h
    core/memory/hpha_schema.cc
    core/memory/malloc_schema.h
    core/memory/malloc_schema.cc
    core/memory/iallocator.h
    core/memory/iallocator.cc
    core/memory/memory.h
    core/memory/memory.cc
    core/memory/osallocator.h
    core/memory/osallocator.cc
    core/memory/platform_memory_instrumentation.h
    core/memory/simple_schema_allocator.h
    core/memory/system_allocator.h
    core/memory/system_allocator.cc
    core/module/environment.h
    core/module/environment.cc
    core/outcome/internal/outcome_storage.h
    core/outcome/outcome.h
    core/platform_id/platform_id.h
    core/platform_id/platform_id.cc
    core/std/bind/bind.h
    core/std/bind/mem_fn.h
    core/std/chrono/chrono.h
    core/std/chrono/clocks.h
    core/std/chrono/types.h
    core/std/containers/array.h
    core/std/containers/deque.h
    core/std/containers/fixed_list.h
    core/std/containers/fixed_vector.h
    core/std/containers/forward_list.h
    core/std/containers/intrusive_list.h
    core/std/containers/intrusive_set.h
    core/std/containers/intrusive_slist.h
    core/std/containers/list.h
    core/std/containers/node_handle.h
    core/std/containers/queue.h
    core/std/containers/set.h
    core/std/containers/stack.h
    core/std/containers/unordered_map.h
    core/std/containers/unordered_set.h
    core/std/containers/vector.h
    core/std/delegate/delegate.h
    core/std/delegate/delegate_bind.h
    core/std/delegate/delegate_fwd.h
    core/std/function/function_base.h
    core/std/function/function_fwd.h
    core/std/function/function_template.h
    core/std/function/identity.h
    core/std/function/invoke.h
    core/std/parallel/atomic.h
    core/std/parallel/combinable.h
    core/std/parallel/condition_variable.h
    core/std/parallel/conditional_variable.h
    core/std/parallel/config.h
    core/std/parallel/exponential_backoff.h
    core/std/parallel/lock.h
    core/std/parallel/mutex.h
    core/std/parallel/scoped_lock.h
    core/std/parallel/semaphore.h
    core/std/parallel/shared_mutex.h
    core/std/parallel/shared_spin_mutex.h
    core/std/parallel/spin_mutex.h
    core/std/parallel/thread.h
    core/std/smart_ptr/checked_delete.h
    core/std/smart_ptr/make_shared.h
    core/std/smart_ptr/shared_count.h
    core/std/smart_ptr/shared_ptr.h
    core/std/smart_ptr/sp_convertible.h
    core/std/smart_ptr/unique_ptr.h
    core/std/smart_ptr/weak_ptr.h
    core/std/string/utf8/core.h
    core/std/string/utf8/unchecked.h
    core/std/string/conversions.h
    core/std/string/fixed_string.h
    core/std/string/string_view.h
    core/std/string/string.h
    core/std/string/string.cc
    core/std/string/tokenize.h
    core/std/string/wildcard.h
    core/std/typetraits/internal/is_template_copy_constructible.h
    core/std/typetraits/internal/type_sequence_traits.h
    core/std/typetraits/add_const.h
    core/std/typetraits/add_cv.h
    core/std/typetraits/add_pointer.h
    core/std/typetraits/add_reference.h
    core/std/typetraits/add_volatile.h
    core/std/typetraits/aligned_storage.h
    core/std/typetraits/alignment_of.h
    core/std/typetraits/common_type.h
    core/std/typetraits/conditional.h
    core/std/typetraits/config.h
    core/std/typetraits/conjunction.h
    core/std/typetraits/decay.h
    core/std/typetraits/disjunction.h
    core/std/typetraits/extent.h
    core/std/typetraits/function_traits.h
    core/std/typetraits/has_member_function.h
    core/std/typetraits/has_virtual_destructor.h
    core/std/typetraits/integral_constant.h
    core/std/typetraits/intrinsics.h
    core/std/typetraits/invoke_traits.h
    core/std/typetraits/is_abstract.h
    core/std/typetraits/is_arithmetic.h
    core/std/typetraits/is_array.h
    core/std/typetraits/is_assignable.h
    core/std/typetraits/is_base_of.h
    core/std/typetraits/is_class.h
    core/std/typetraits/is_compound.h
    core/std/typetraits/is_const.h
    core/std/typetraits/is_constructible.h
    core/std/typetraits/is_convertible.h
    core/std/typetraits/is_destructible.h
    core/std/typetraits/is_empty.h
    core/std/typetraits/is_enum.h
    core/std/typetraits/is_floating_point.h
    core/std/typetraits/is_function.h
    core/std/typetraits/is_fundamental.h
    core/std/typetraits/is_integral.h
    core/std/typetraits/is_lvalue_reference.h
    core/std/typetraits/is_member_function_pointer.h
    core/std/typetraits/is_member_object_pointer.h
    core/std/typetraits/is_object.h
    core/std/typetraits/is_pod.h
    core/std/typetraits/is_pointer.h
    core/std/typetraits/is_polymorphic.h
    core/std/typetraits/is_reference.h
    core/std/typetraits/is_rvalue_reference.h
    core/std/typetraits/is_same.h
    core/std/typetraits/is_scalar.h
    core/std/typetraits/is_signed.h
    core/std/typetraits/is_swappable.h
    core/std/typetraits/is_trivial.h
    core/std/typetraits/is_trivially_copyable.h
    core/std/typetraits/is_union.h
    core/std/typetraits/is_unsigned.h
    core/std/typetraits/is_void.h
    core/std/typetraits/is_unsigned.h
    core/std/typetraits/is_void.h
    core/std/typetraits/is_volatile.h
    core/std/typetraits/negation.h
    core/std/typetraits/rank.h
    core/std/typetraits/remove_all_extents.h
    core/std/typetraits/remove_const.h
    core/std/typetraits/remove_cv.h
    core/std/typetraits/remove_cvref.h
    core/std/typetraits/remove_extent.h
    core/std/typetraits/remove_pointer.h
    core/std/typetraits/remove_reference.h
    core/std/typetraits/remove_volatile.h
    core/std/typetraits/static_storage.h
    core/std/typetraits/tuple_traits.h
    core/std/typetraits/type_id.h
    core/std/typetraits/type_identity.h
    core/std/typetraits/typetraits.h
    core/std/typetraits/underlying_type.h
    core/std/typetraits/void_t.h
    core/std/algorithm.h
    core/std/allocator_ref.h
    core/std/allocator_static.h
    core/std/allocator_traits.h
    core/std/allocator.h
    core/std/allocator.cc
    core/std/base.h
    core/std/config.h
    core/std/createdestroy.h
    core/std/exceptions.h
    core/std/functional_basic.h
    core/std/functional.h
    core/std/hash_table.h
    core/std/hash.h
    core/std/hash.cc
    core/std/iterator.h
    core/std/limits.h
    core/std/math.h
    core/std/numeric.h
    core/std/optional.h
    core/std/ratio.h
    core/std/reference_wrapper.h
    core/std/time.h
    core/std/tuple.h
    core/std/typeinfo.h
    core/std/utils.h
    core/string_func/string_func.h
    core/string_func/string_func.cc
    core/utilitys/utility.h
    core/utilitys/utility.cc
)