SET (FILES
    platforms/windows/vcore/traits_platform.h
    platforms/windows/vcore/traits_windows.h
    platforms/windows/vcore/base_platform.h
    platforms/windows/vcore/base_windows.h
    platforms/windows/vcore/platform_incl_platform.h
    platforms/windows/vcore/platform_incl_windows.h
    platforms/windows/vcore/platform_windows.cc
    platforms/windows/vcore/platform_id/platform_id_platform.h
    platforms/windows/vcore/platform_id/platform_id_windows.inl
    platforms/windows/vcore/math/internal/math_types_platform.h
    platforms/windows/vcore/math/internal/math_types_windows.h
    platforms/windows/vcore/math/random_platform.h
    platforms/windows/vcore/math/random_windows.h
    platforms/windows/vcore/math/random_windows.cc
    platforms/windows/vcore/debug/stacktracer_windows.cc
    platforms/windows/vcore/ipc/shared_memory_platform.h
    platforms/windows/vcore/ipc/shared_memory_windows.h
    platforms/windows/vcore/ipc/shared_memory_windows.cc
    platforms/windows/vcore/std/parallel/internal/condition_variable_platform.h
    platforms/windows/vcore/std/parallel/internal/mutex_platform.h
    platforms/windows/vcore/std/parallel/internal/semaphore_platform.h
    platforms/windows/vcore/std/parallel/internal/thread_platform.h
    platforms/windows/vcore/std/parallel/config_platform.h
    platforms/windows/vcore/std/string/fixed_string_platform.inl
    platforms/common/winapi/vcore/std/time_windows.cc
    platforms/common/winapi/vcore/std/parallel/internal/condition_variable_winapi.inl
    platforms/common/winapi/vcore/std/parallel/internal/mutex_winapi.inl
    platforms/common/winapi/vcore/std/parallel/internal/semaphore_winapi.inl
    platforms/common/winapi/vcore/std/parallel/internal/thread_winapi.h
    platforms/common/winapi/vcore/std/parallel/internal/thread_winapi.cc
    platforms/common/winapi/vcore/std/parallel/config_platform.h
    platforms/common/winapi/vcore/std/parallel/config_winapi.h
    platforms/common/winapi/vcore/memory/osallocator_winapi.inl
    platforms/common/winapi/vcore/io/system_file_winapi.h
    platforms/common/winapi/vcore/io/system_file_winapi.cc
    platforms/common/winapi/vcore/utilitys/utility_winapi.cc
)