#ifndef V_FRAMEWORK_PLATFORMS_WINDOWS_CORE_SOCKET_VSOCKET_FWD_WINDOWS_H
#define V_FRAMEWORK_PLATFORMS_WINDOWS_CORE_SOCKET_VSOCKET_FWD_WINDOWS_H

#include <../common/winapi/vcore/socket/vsocket_fwd_winapi.h>
#define WIN_SOCK_LIB_TO_LINK "WS2_32.lib"

#endif // V_FRAMEWORK_PLATFORMS_WINDOWS_CORE_SOCKET_VSOCKET_FWD_WINDOWS_H