SET(FILES
    vcore/base.h
    vcore/platform_default.h
    vcore/platform_incl.h
    vcore/platform_restricted_file_default.h
    vcore/platform.h
    vcore/platform.cc
    vcore/variadic.h
    vcore/debug/trace.h
    vcore/std/base.h
    vcore/std/config.h
    vcore/std/algorithm.h
    vcore/std/allocator_ref.h
    vcore/std/allocator_static.h
    vcore/std/allocator_traits.h
    vcore/std/allocator.h
    vcore/std/allocator.cc
    vcore/std/createdestroy.h
    vcore/std/exceptions.h
    vcore/std/functional_basic.h
    vcore/std/functional.h
    vcore/std/hash.h
    vcore/std/hash.cc
    vcore/std/iterator.h
    vcore/std/limits.h
    vcore/std/math.h
    vcore/std/numeric.h
    vcore/std/optional.h
    vcore/std/reference_wrapper.h
    vcore/std/ratio.h
    vcore/std/time.h
    vcore/std/tuple.h
    vcore/std/utils.h
    vcore/std/bind/bind.h
    vcore/std/bind/mem_fn.h
    vcore/std/chrono/chrono.h
    vcore/std/chrono/clocks.h
    vcore/std/chrono/types.h
    vcore/std/containers/array.h
    vcore/std/function/function_base.h
    vcore/std/function/function_fwd.h
    vcore/std/function/function_template.h
    vcore/std/function/identity.h
    vcore/std/function/invoke.h
    vcore/std/typetraits/internal/is_template_copy_constructible.h
    vcore/std/typetraits/internal/type_sequence_traits.h
    vcore/std/typetraits/add_const.h
    vcore/std/typetraits/add_cv.h
    vcore/std/typetraits/add_pointer.h
    vcore/std/typetraits/add_reference.h
    vcore/std/typetraits/add_volatile.h
    vcore/std/typetraits/aligned_storage.h
    vcore/std/typetraits/alignment_of.h
    vcore/std/typetraits/common_type.h
    vcore/std/typetraits/conditional.h
    vcore/std/typetraits/config.h
    vcore/std/typetraits/conjunction.h
    vcore/std/typetraits/decay.h
    vcore/std/typetraits/disjunction.h
    vcore/std/typetraits/extent.h
    vcore/std/typetraits/function_traits.h
    vcore/std/typetraits/has_member_function.h
    vcore/std/typetraits/has_virtual_destructor.h
    vcore/std/typetraits/integral_constant.h
    vcore/std/typetraits/intrinsics.h
    vcore/std/typetraits/invoke_traits.h
    vcore/std/typetraits/is_abstract.h
    vcore/std/typetraits/is_arithmetic.h
    vcore/std/typetraits/is_array.h
    vcore/std/typetraits/is_assignable.h
    vcore/std/typetraits/is_base_of.h
    vcore/std/typetraits/is_class.h
    vcore/std/typetraits/is_compound.h
    vcore/std/typetraits/is_const.h
    vcore/std/typetraits/is_constructible.h
    vcore/std/typetraits/is_convertible.h
    vcore/std/typetraits/is_destructible.h
    vcore/std/typetraits/is_empty.h
    vcore/std/typetraits/is_enum.h
    vcore/std/typetraits/is_floating_point.h
    vcore/std/typetraits/is_function.h
    vcore/std/typetraits/is_fundamental.h
    vcore/std/typetraits/is_integral.h
    vcore/std/typetraits/is_lvalue_reference.h
    vcore/std/typetraits/is_member_function_pointer.h
    vcore/std/typetraits/is_member_object_pointer.h
    vcore/std/typetraits/is_member_pointer.h
    vcore/std/typetraits/is_object.h
    vcore/std/typetraits/is_pod.h
    vcore/std/typetraits/is_pointer.h
    vcore/std/typetraits/is_polymorphic.h
    vcore/std/typetraits/is_reference.h
    vcore/std/typetraits/is_rvalue_reference.h
    vcore/std/typetraits/is_same.h
    vcore/std/typetraits/is_scalar.h
    vcore/std/typetraits/is_swappable.h
    vcore/std/typetraits/is_trivial.h
    vcore/std/typetraits/is_trivially_copyable.h
    vcore/std/typetraits/is_type_safe_integral.h
    vcore/std/typetraits/is_union.h
    vcore/std/typetraits/is_unsigned.h
    vcore/std/typetraits/is_void.h
    vcore/std/typetraits/is_volatile.h
    vcore/std/typetraits/negation.h
    vcore/std/typetraits/rank.h
    vcore/std/typetraits/remove_all_extents.h
    vcore/std/typetraits/remove_const.h
    vcore/std/typetraits/remove_cv.h
    vcore/std/typetraits/remove_cvref.h
    vcore/std/typetraits/remove_extent.h
    vcore/std/typetraits/remove_pointer.h
    vcore/std/typetraits/remove_reference.h
    vcore/std/typetraits/remove_volatile.h
    vcore/std/typetraits/static_storage.h
    vcore/std/typetraits/tuple_traits.h
    vcore/std/typetraits/type_id.h
    vcore/std/typetraits/type_identity.h
    vcore/std/typetraits/typetraits.h
    vcore/std/typetraits/underlying_type.h
    vcore/std/typetraits/void_t.h
)