SET(FILES
    vcore/base.h
    vcore/platform_default.h
    vcore/platform_incl.h
    vcore/platform_restricted_file_default.h
    vcore/platform.h
    vcore/platform.cc
    vcore/variadic.h
    vcore/casting/lossy_cast.h
    vcore/casting/numeric_cast_internal.h
    vcore/casting/numeric_cast.h
    vcore/interface/interface.h
    vcore/io/path/path_fwd.h
    vcore/io/path/path.h
    vcore/io/path/path.cc
    vcore/io/file_io.h
    vcore/io/file_io.cc
    vcore/io/generic_streams.h
    vcore/io/generic_streams.cc
    vcore/io/io_utils.h
    vcore/io/io_utils.cc
    vcore/io/system_file.h
    vcore/io/system_file.cc
    vcore/ipc/shared_memory_common.h
    vcore/ipc/shared_memory.h
    vcore/ipc/shared_memory.cc
    vcore/math/internal/math_type.h
    vcore/math/internal/simd.h
    vcore/math/crc.h
    vcore/math/crc.cc
    vcore/math/guid.h 
    vcore/math/math_utils.h
    vcore/math/random.h
    vcore/math/sfmt.h 
    vcore/math/sfmt.cc
    vcore/math/sha1.h 
    vcore/math/type_id.h
    vcore/math/uuid.h
    vcore/math/uuid.cc
    vcore/module/environment.h
    vcore/module/environment.cc
    vcore/module/dynamic_module_handle.h
    vcore/module/dynamic_module_handle.cc
    vcore/name/internal/name_data.h
    vcore/name/internal/name_data.cc
    vcore/name/name_dictionary.h
    vcore/name/name_dictionary.cc
    vcore/name/name.h
    vcore/name/name.cc
    vcore/memory/system_allocator.h
    vcore/memory/system_allocator.cc
    vcore/memory/allocator_base.h
    vcore/memory/allocator_base.cc
    vcore/memory/allocator_manager.h
    vcore/memory/allocator_records.h
    vcore/memory/allocator_records.cc
    vcore/memory/allocator_manager.cc
    vcore/memory/allocator_override_shim.h
    vcore/memory/allocator_override_shim.cc
    vcore/memory/allocator_wrapper.h
    vcore/memory/config.h
    vcore/memory/heap_schema.h
    vcore/memory/heap_schema.cc
    vcore/memory/hpha_schema.h
    vcore/memory/hpha_schema.cc
    vcore/memory/iallocator.h
    vcore/memory/iallocator.cc
    vcore/memory/malloc_schema.h
    vcore/memory/malloc_schema.cc
    vcore/memory/memory.h
    vcore/memory/memory.cc
    vcore/memory/osallocator.h
    vcore/memory/osallocator.cc
    vcore/memory/platform_memory_instrumentation.h
    vcore/memory/simple_schema_allocator.h
    vcore/event_bus/internal/bus_container.h
    vcore/event_bus/internal/call_stack_entry.h
    vcore/event_bus/internal/debug.h
    vcore/event_bus/internal/handlers.h
    vcore/event_bus/internal/storage_policies.h
    vcore/event_bus/bus_impl.h
    vcore/event_bus/environment.h
    vcore/event_bus/event_bus_shared_dispatch_traits.h
    vcore/event_bus/event_bus_environment.cc
    vcore/event_bus/event_bus.h
    vcore/event_bus/event.h
    vcore/event_bus/ievent_scheduler.h
    vcore/event_bus/ordered_event.h
    vcore/event_bus/policies.h
    vcore/event_bus/results.h
    vcore/event_bus/scheduled_event_handle.h
    vcore/event_bus/scheduled_event_handle.cc
    vcore/event_bus/scheduled_event.h
    vcore/event_bus/scheduled_event.cc
    vcore/outcome/internal/outcome_storage.h
    vcore/outcome/outcome.h
    vcore/vobject/type.h
    vcore/vobject/type_simple.h
    vcore/vobject/type_safe_integral.h
    vcore/vobject/vobject.h
    vcore/debug/ievent_logger.h
    vcore/debug/trace.h
    vcore/debug/trace.cc
    vcore/compression/compression.h
    vcore/compression/compression.cc
    vcore/compression/zstd_compression.h
    vcore/compression/zstd_compression.cc
    vcore/detector/default_string_pool.h
    vcore/detector/detector_bus.h
    vcore/detector/detector_bus.cc
    vcore/detector/detector.h
    vcore/detector/detector.cc
    vcore/detector/stream.h
    vcore/detector/stream.cc
    vcore/time/itime.h
    vcore/std/base.h
    vcore/std/config.h
    vcore/std/algorithm.h
    vcore/std/allocator_ref.h
    vcore/std/allocator_static.h
    vcore/std/allocator_traits.h
    vcore/std/allocator.h
    vcore/std/allocator.cc
    vcore/std/createdestroy.h
    vcore/std/exceptions.h
    vcore/std/functional_basic.h
    vcore/std/functional.h
    vcore/std/hash_table.h
    vcore/std/hash.h
    vcore/std/hash.cc
    vcore/std/iterator.h
    vcore/std/limits.h
    vcore/std/math.h
    vcore/std/numeric.h
    vcore/std/optional.h
    vcore/std/reference_wrapper.h
    vcore/std/ratio.h
    vcore/std/time.h
    vcore/std/tuple.h
    vcore/std/utils.h
    vcore/std/bind/bind.h
    vcore/std/bind/mem_fn.h
    vcore/std/chrono/chrono.h
    vcore/std/chrono/clocks.h
    vcore/std/chrono/types.h
    vcore/std/containers/array.h
    vcore/std/containers/bitset.h
    vcore/std/containers/compressed_pair.h
    vcore/std/containers/deque.h
    vcore/std/containers/fixed_forward_list.h
    vcore/std/containers/fixed_list.h
    vcore/std/containers/fixed_unordered_map.h
    vcore/std/containers/fixed_unordered_set.h
    vcore/std/containers/fixed_vector.h
    vcore/std/containers/forward_list.h
    vcore/std/containers/intrusive_list.h
    vcore/std/containers/intrusive_set.h
    vcore/std/containers/intrusive_slist.h
    vcore/std/containers/list.h
    vcore/std/containers/map.h
    vcore/std/containers/node_handle.h
    vcore/std/containers/queue.h
    vcore/std/containers/rbtree.h
    vcore/std/containers/set.h
    vcore/std/containers/stack.h
    vcore/std/containers/unordered_map.h
    vcore/std/containers/unordered_set.h
    vcore/std/containers/vector.h
    vcore/std/containers/variant_impl.h
    vcore/std/containers/variant.h
    vcore/std/delegate/delegate_bind.h
    vcore/std/delegate/delegate_fwd.h
    vcore/std/delegate/delegate.h
    vcore/std/function/function_base.h
    vcore/std/function/function_fwd.h
    vcore/std/function/function_template.h
    vcore/std/function/identity.h
    vcore/std/function/invoke.h
    vcore/std/parallel/atomic.h
    vcore/std/parallel/combinable.h
    vcore/std/parallel/condition_variable.h
    vcore/std/parallel/conditional_variable.h
    vcore/std/parallel/config.h
    vcore/std/parallel/exponential_backoff.h
    vcore/std/parallel/lock.h
    vcore/std/parallel/mutex.h
    vcore/std/parallel/scoped_lock.h
    vcore/std/parallel/semaphore.h
    vcore/std/parallel/shared_mutex.h
    vcore/std/parallel/shared_spin_mutex.h
    vcore/std/parallel/spin_mutex.h
    vcore/std/parallel/thread.h
    vcore/std/smart_ptr/checked_delete.h
    vcore/std/smart_ptr/intrusive_base.h
    vcore/std/smart_ptr/intrusive_ptr.h
    vcore/std/smart_ptr/intrusive_refcount.h
    vcore/std/smart_ptr/make_shared.h
    vcore/std/smart_ptr/shared_count.h
    vcore/std/smart_ptr/shared_ptr.h
    vcore/std/smart_ptr/sp_convertible.h
    vcore/std/smart_ptr/unique_ptr.h
    vcore/std/smart_ptr/weak_ptr.h
    vcore/std/typetraits/internal/is_template_copy_constructible.h
    vcore/std/typetraits/internal/type_sequence_traits.h
    vcore/std/typetraits/add_const.h
    vcore/std/typetraits/add_cv.h
    vcore/std/typetraits/add_pointer.h
    vcore/std/typetraits/add_reference.h
    vcore/std/typetraits/add_volatile.h
    vcore/std/typetraits/aligned_storage.h
    vcore/std/typetraits/alignment_of.h
    vcore/std/typetraits/common_type.h
    vcore/std/typetraits/conditional.h
    vcore/std/typetraits/config.h
    vcore/std/typetraits/conjunction.h
    vcore/std/typetraits/decay.h
    vcore/std/typetraits/disjunction.h
    vcore/std/typetraits/extent.h
    vcore/std/typetraits/function_traits.h
    vcore/std/typetraits/has_member_function.h
    vcore/std/typetraits/has_virtual_destructor.h
    vcore/std/typetraits/integral_constant.h
    vcore/std/typetraits/intrinsics.h
    vcore/std/typetraits/invoke_traits.h
    vcore/std/typetraits/is_abstract.h
    vcore/std/typetraits/is_arithmetic.h
    vcore/std/typetraits/is_array.h
    vcore/std/typetraits/is_assignable.h
    vcore/std/typetraits/is_base_of.h
    vcore/std/typetraits/is_class.h
    vcore/std/typetraits/is_compound.h
    vcore/std/typetraits/is_const.h
    vcore/std/typetraits/is_constructible.h
    vcore/std/typetraits/is_convertible.h
    vcore/std/typetraits/is_destructible.h
    vcore/std/typetraits/is_empty.h
    vcore/std/typetraits/is_enum.h
    vcore/std/typetraits/is_floating_point.h
    vcore/std/typetraits/is_function.h
    vcore/std/typetraits/is_fundamental.h
    vcore/std/typetraits/is_integral.h
    vcore/std/typetraits/is_lvalue_reference.h
    vcore/std/typetraits/is_member_function_pointer.h
    vcore/std/typetraits/is_member_object_pointer.h
    vcore/std/typetraits/is_member_pointer.h
    vcore/std/typetraits/is_object.h
    vcore/std/typetraits/is_pod.h
    vcore/std/typetraits/is_pointer.h
    vcore/std/typetraits/is_polymorphic.h
    vcore/std/typetraits/is_reference.h
    vcore/std/typetraits/is_rvalue_reference.h
    vcore/std/typetraits/is_same.h
    vcore/std/typetraits/is_scalar.h
    vcore/std/typetraits/is_swappable.h
    vcore/std/typetraits/is_trivial.h
    vcore/std/typetraits/is_trivially_copyable.h
    vcore/std/typetraits/is_type_safe_integral.h
    vcore/std/typetraits/is_union.h
    vcore/std/typetraits/is_unsigned.h
    vcore/std/typetraits/is_void.h
    vcore/std/typetraits/is_volatile.h
    vcore/std/typetraits/negation.h
    vcore/std/typetraits/rank.h
    vcore/std/typetraits/remove_all_extents.h
    vcore/std/typetraits/remove_const.h
    vcore/std/typetraits/remove_cv.h
    vcore/std/typetraits/remove_cvref.h
    vcore/std/typetraits/remove_extent.h
    vcore/std/typetraits/remove_pointer.h
    vcore/std/typetraits/remove_reference.h
    vcore/std/typetraits/remove_volatile.h
    vcore/std/typetraits/static_storage.h
    vcore/std/typetraits/tuple_traits.h
    vcore/std/typetraits/type_id.h
    vcore/std/typetraits/type_identity.h
    vcore/std/typetraits/typetraits.h
    vcore/std/typetraits/underlying_type.h
    vcore/std/typetraits/void_t.h
    vcore/string_func/string_func.h
    vcore/string_func/string_func.cc
    vcore/utilitys/city.h
    vcore/utilitys/city.cc
    vcore/utilitys/citycrc.h
    vcore/utilitys/type_hash.h
    vcore/utilitys/type_hash.cc
    vcore/utilitys/utility.h
    vcore/utilitys/utility.cc
    vcore/platform_id/platform_id.cc
    vcore/platform_id/platform_id.h 
)